### ISSUE TITLE
Suggestions 🗹: checklist and improvements from '19

### ISSUE THREAD

**Issue by jishanshaikh4** [jishanshaikh4/ml-papers-22#1]
- [ ] Numbering of date folders (tag:easy)
- [ ] Topic balance (tag:medium)
- [ ] Expertise balance (tag:medium)
- [ ] Mathematical balance (tag:hard)
- [ ] Topic wise ordering with symlinks (tag:easy)

For more info, see ['19](https://github.com/jishanshaikh4/ml-papers).
